services:
    postgres:
        ports:
            - '5432:5432'

    valkey:
        ports:
            - '6379:6379'

    meilisearch:
        ports:
            - '7700:7700'

    tika:
        ports:
            - '9998:9998'
